name: Drupal coding standards

on:
  pull_request:
    paths-ignore:
      - "**/libraries/**"
      - "**/node_modules/**"
      - "**/source/**"
      - "**/vendor/**"

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 0 indicates all history for all branches and tags.

      # Need to install Composer to be able to add the coding standards rules.
      - name: Installing Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"

      - name: Downloading and installing PHP_CodeSniffer and the Drupal coding standards rules
        run: |
          php composer.phar global require --optimize-autoloader --sort-packages squizlabs/php_codesniffer=* drupal/coder "slevomat/coding-standard:^6.0" "dealerdirect/phpcodesniffer-composer-installer:^0.7"
          export PATH="$HOME/.composer/vendor/bin:$PATH"

      - name: Checking coding standards
        uses: thenabeel/action-phpcs@v8
        with:
          files: "**.inc,**.install,**.md,**.module,**.php,**.profile,**.test,**.txt,**.theme,**.yml"
          phpcs_path: $HOME/.composer/vendor/bin/phpcs
          standard: phpcs.xml
          scope: files
